# build env
FROM node:12.8.0 as builder

WORKDIR /app

COPY package.json ./
RUN npm install --legacy-peer-deps \
  && npm install --save-dev @types/jquery@3.5.14 @types/ws@7.4.7 --legacy-peer-deps \
  && npm install angular-file@3.0.12 --legacy-peer-deps
COPY . .

# Build Angular Application in Production
RUN export NODE_OPTIONS=--max-old-space-size=4096
RUN node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod
RUN ls -al

#### STAGE 2
#### Deploying the application

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Copy Nginx Files
COPY --from=builder /app/docker/nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE Port 80
# EXPOSE 80
CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]